eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
# Application name and Service routes
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route to product_service
      - id: product_service
        uri: lb://product-service
        predicates:
          - Path=/api/product
        # Route to order_service
      - id: order_service
        uri: lb://order_service
        predicates:
          - Path=/api/order
        # Route to inventory_service
      - id: inventory_service
        uri: lb://inventory_service
        predicates:
          - Path=/api/inventory
        # Route to discovery server web
      - id: discover_server
        uri: http://localhost:8761
        predicates:
          - Path=/eureka/web
        filters:
          - SetPath=/

      # Route to discovery server static resources
      - id: discover_server
        uri: http://localhost:8761
        predicates:
          - Path=/eureka/**


logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: trace

