eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
# Application name and Service routes
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route to product_service
      - id: product-service
        uri: lb://product-service
        predicates:
          - Path=/api/product
        # Route to order_service
      - id: order-service
        uri: lb://order-service
        predicates:
          - Path=/api/order
        # Route to inventory_service
      - id: inventory-service
        uri: lb://inventory-service
        predicates:
          - Path=/api/inventory
        # Route to discovery server web
      - id: discover-server
        uri: http://localhost:8761
        predicates:
          - Path=/eureka/web
        filters:
          - SetPath=/

      # Route to discovery server static resources
      - id: discover_server
        uri: http://localhost:8761
        predicates:
          - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/spring-boot-microservices-realm


logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: trace

